### ISSUE TITLE
Promises?

### ISSUE THREAD

**Issue by bates64** [s3ththompson/nanofetch#1]
Would be great if `Nanofetcher.prototype.fetch()` could instead return a Promise (as opposed to callback) if the navigator has them.

**Comment by s3ththompson** [comment]
Yeah it should be possible to check if fetch returned a promise without too much difficulty and then wait for it to resolve instead of expecting the callback to be returned.

Out of curiosity, are you trying to avoid the verbosity of the following?
```js
Nanofetcher.prototype.fetch = function (cb) {
  asyncData().then(cb)
}
```

**Comment by bates64** [comment]
Awesome.

>Out of curiosity, are you trying to avoid the verbosity of the following?

Yep:

```js
Nanofetcher.prototype.fetch = function (cb) {
  asyncData()
    .then(data => cb(null, data))
    .catch(err => cb(err))
}
```

**Comment by s3ththompson** [comment]
Let me know if this works for your use case.

**Comment by bates64** [comment]
This looks great 😁

Thank you.
